Repository bilalkah/path-planning, pull requests merged in 2023-09, with the labels that each got.

#3 Workspace reconfigure and directions update
  .vscode/tasks.json
  CMakeLists.txt
  main.cpp
  planning/CMakeLists.txt
  planning/common_planning.h
  planning/grid_base/CMakeLists.txt
  planning/grid_base/a_star/CMakeLists.txt
  planning/grid_base/a_star/a_star.cpp
  planning/grid_base/a_star/a_star.h
  planning/grid_base/bfs/CMakeLists.txt
  planning/grid_base/bfs/bfs.cpp
  planning/grid_base/bfs/bfs.h
  planning/grid_base/common_grid_base.h
  planning/grid_base/dfs/CMakeLists.txt
  planning/grid_base/dfs/dfs.cpp
  planning/grid_base/dfs/dfs.h
  planning/grid_base/include/common_grid_base.h
  planning/grid_base/src/common_grid_base.cpp
  planning/include/common_planning.h
  planning/include/data_types.h
  planning/include/i_planning.h
  planning/include/node_parent.h
  planning/src/common_planning.cpp
  planning/tree_base/CMakeLists.txt
  planning/tree_base/rrt/CMakeLists.txt
  test/CMakeLists.txt
  test/test_a_star.cpp
  test/test_access_data.cpp
  test/test_bfs.cpp
  test/test_dfs.cpp
  test/test_fixture.h
  test/test_map.cpp
Labels: bug

#4 CI Update
  .github/workflows/cmake-single-platform.yml
Labels: ci

#5 Ft lambda improve
  planning/grid_base/a_star/a_star.cpp
Labels: ci

#6 Apply clang format
  .github/workflows/cmake-single-platform.yml
  .github/workflows/lint.yml
  .vscode/launch.json
  .vscode/tasks.json
  CMakeLists.txt
  main.cpp
  planning/grid_base/CMakeLists.txt
  planning/grid_base/a_star/a_star.cpp
  planning/grid_base/a_star/a_star.h
  planning/grid_base/bfs/CMakeLists.txt
  planning/grid_base/bfs/bfs.cpp
  planning/grid_base/bfs/bfs.h
  planning/grid_base/dfs/dfs.cpp
  planning/grid_base/dfs/dfs.h
  planning/grid_base/include/common_grid_base.h
  planning/grid_base/src/common_grid_base.cpp
  planning/include/data_types.h
  planning/include/i_planning.h
  planning/include/node_parent.h
  planning/tree_base/CMakeLists.txt
  planning/tree_base/rrt/CMakeLists.txt
  planning/tree_base/rrt/rrt.cpp
  planning/tree_base/rrt/rrt.h
  test/test_a_star.cpp
  test/test_bfs.cpp
  test/test_dfs.cpp
  test/test_fixture.h
  test/test_map.cpp
Labels: ci

#7 CI Fix
  .github/workflows/cmake-single-platform.yml
  .github/workflows/lint.yml
Labels: ci

#9 Custom visualization library for path planning
  CMakeLists.txt
  main.cpp
  planning/grid_base/a_star/a_star.cpp
  planning/grid_base/a_star/a_star.h
  planning/grid_base/bfs/bfs.cpp
  planning/grid_base/bfs/bfs.h
  planning/grid_base/dfs/dfs.cpp
  planning/grid_base/dfs/dfs.h
  planning/include/data_types.h
  planning/include/i_planning.h
  tools/CMakeLists.txt
  tools/include/visualizer.h
  tools/src/visualizer.cpp
Labels: ci

#10 A Star algorithm bug fix and visualizer clean up
  main.cpp
  planning/grid_base/a_star/a_star.cpp
  planning/include/common_planning.h
  planning/src/common_planning.cpp
  test/test_fixture.h
  test/test_map.cpp
  tools/src/visualizer.cpp
Labels: ci

#12 Change planner constructors
  main.cpp
  planning/grid_base/a_star/a_star.cpp
  planning/grid_base/a_star/a_star.h
  planning/grid_base/bfs/bfs.cpp
  planning/grid_base/bfs/bfs.h
  planning/grid_base/dfs/dfs.cpp
  planning/grid_base/dfs/dfs.h
  planning/grid_base/include/common_grid_base.h
  planning/grid_base/src/common_grid_base.cpp
  test/test_a_star.cpp
  test/test_bfs.cpp
  test/test_dfs.cpp
Labels: ci

#14 Reorder and remove unnecessary
  planning/grid_base/a_star/a_star.cpp
  planning/grid_base/bfs/bfs.cpp
  planning/grid_base/dfs/dfs.cpp
  planning/grid_base/include/common_grid_base.h
  planning/tree_base/rrt/rrt.cpp
  tools/include/visualizer.h
Labels: ci

#15 RRT Bug Fix
  planning/include/data_types.h
  planning/tree_base/include/common_tree_base.h
  planning/tree_base/rrt/rrt.cpp
  planning/tree_base/rrt/rrt.h
  planning/tree_base/src/common_tree_base.cpp
Labels: ci

#16 Bf rrt star
  config/main.yaml
  main.cpp
  planning/include/node_parent.h
  planning/tree_base/rrt/rrt.cpp
  planning/tree_base/rrt_star/rrt_star.cpp
  planning/tree_base/rrt_star/rrt_star.h
  tools/include/visualizer.h
  tools/src/visualizer.cpp
Labels: ci

#17 Update Readme
  README.md
  images/astar.png
  images/bfs.png
  images/rrt.png
  images/rrt_star.png
Labels: documentation
